import { test } from 'node:test';
import assert from 'node:assert/strict';
import { io, type Socket } from 'socket.io-client';
import { startServers } from '../src/server/index';
import { get } from 'node:http';
import type { SessionView, Reply, Action, RoomView, LobbyView } from '../src/shared/protocol';
import { GAME_VERSION } from '../src/shared/version';
async function connect(url: string, token?: string) { return new Promise<{ socket: Socket; session: SessionView }>((resolve, reject) => { const socket = io(url, { transports: ['websocket'], auth: token ? { token } : {}, reconnection: false }); socket.once('session', session => resolve({ socket, session })); socket.once('connect_error', error => { socket.close(); reject(error); }); }); }
async function send(socket: Socket, action: Action) { return new Promise<Reply>((resolve, reject) => socket.timeout(2000).emit('action', action, (e: Error, r: Reply) => e ? reject(e) : resolve(r))); }
test('host tunnel rebuild aborts rounds, clears credentials, keeps settings and rejects stale/duplicate updates', async t => {
  const requests: number[] = [];
  const server = await startServers({ onRebuildTunnel: generation => { requests.push(generation); } }); t.after(() => server.stop());
  server.engine.defaultDuration = 90; server.engine.allowSurrender = true; server.engine.setUltimateMode(true);
  server.setTunnel('https://old-game.trycloudflare.com', 'ready');
  const host = new URL(server.hostUrl).origin, login = await fetch(server.hostUrl, { redirect: 'manual' });
  const cookie = login.headers.get('set-cookie')!.split(';')[0];
  const post = (kind = 'rebuild-tunnel', auth = true, origin = host) => fetch(host + '/api/host/action', { method: 'POST', headers: { ...(auth ? { Cookie: cookie } : {}), Origin: origin, 'Content-Type': 'application/json' }, body: JSON.stringify({ kind, value: true }) });
  const state = () => fetch(host + '/api/host/state', { headers: { Cookie: cookie } }).then(r => r.json());
  const a = await connect(server.playerUrl); t.after(() => a.socket.close());
  await send(a.socket, { kind: 'create', mode: 'solo', role: 'attack', duration: 30, startImmediately: true });
  const room = server.engine.rooms.get(server.engine.playerView(a.session.id)!.id)!;
  room.deadline = performance.now(); server.engine.advance();
  const oldCode = room.code;
  assert.equal((await post('rebuild-tunnel', false)).status, 403);
  assert.equal((await post('rebuild-tunnel', true, 'https://evil.example')).status, 403);
  assert.equal(requests.length, 0); assert.equal(room.phase, 'playing');
  const resetNotice = new Promise<void>(resolve => a.socket.once('hosting-reset', resolve));
  const ended = new Promise<RoomView>(resolve => a.socket.on('room', r => { if (r?.phase === 'ended') resolve(r); }));
  assert.equal((await post()).status, 200); await resetNotice;
  assert.equal((await ended).winner, null); assert.match(room.reason, /不計勝負/);
  assert.equal(server.engine.rooms.size, 0); assert.equal(server.engine.players.size, 0);
  assert.equal((await post()).status, 400); assert.deepEqual(requests, [1]);
  assert.equal((await post('accepting')).status, 400);
  assert.equal((await state()).lobby.joinUrl, ''); assert.equal((await state()).tunnelControl.busy, true);
  await assert.rejects(() => connect(server.playerUrl));
  server.setTunnel('https://old-game.trycloudflare.com', 'late old health', 0, 'ready');
  assert.equal(server.engine.joinUrl, '');
  server.setTunnel('', '模擬失敗', 1, 'failed');
  assert.equal((await state()).tunnelControl.failed, true); assert.equal(server.engine.accepting, false);
  assert.equal((await post()).status, 200); assert.deepEqual(requests, [1, 2]);
  server.setTunnel('https://stale-game.trycloudflare.com', 'late prior attempt', 1, 'ready');
  assert.equal(server.engine.joinUrl, '');
  server.setTunnel('https://new-game.trycloudflare.com', 'ready', 2, 'ready');
  assert.equal(server.engine.accepting, true); assert.equal((await state()).tunnelControl.busy, false);
  await assert.rejects(() => connect(server.playerUrl, a.session.token));
  const b = await connect(server.playerUrl); t.after(() => b.socket.close());
  await send(b.socket, { kind: 'create', mode: 'solo', role: 'defense', duration: 90 });
  assert.notEqual(server.engine.playerView(b.session.id)!.code, oldCode);
  assert.equal(server.engine.defaultDuration, 90); assert.equal(server.engine.allowSurrender, true); assert.equal(server.engine.lobby().ultimateMode, true);
  server.engine.accepting = false;
  await post(); server.setTunnel('https://next-game.trycloudflare.com', 'ready', 3, 'ready');
  assert.equal(server.engine.accepting, false, 'preserve host choice to pause new admission');
});
test('local-only servers refuse rebuild without clearing rooms', async t => {
  const server = await startServers(); t.after(() => server.stop());
  const p = server.engine.connect(); server.engine.action(p.id, { kind: 'create', mode: 'solo', role: 'attack', duration: 60 });
  const login = await fetch(server.hostUrl, { redirect: 'manual' });
  const host = new URL(server.hostUrl).origin;
  const result = await fetch(host + '/api/host/action', { method: 'POST', headers: { Cookie: login.headers.get('set-cookie')!.split(';')[0], Origin: host, 'Content-Type': 'application/json' }, body: JSON.stringify({ kind: 'rebuild-tunnel' }) });
  assert.equal(result.status, 400); assert.equal(server.engine.rooms.size, 1);
});
test('public endpoint isolates host controls; host requires private cookie and exact origin', async t => {
  const server = await startServers(); t.after(() => server.stop());
  assert.equal((await fetch(server.playerUrl + '/api/health')).status, 200);
  for (const path of ['/host.html', '/../package.json', '/scripts/launch.mjs', '/.runtime/instance.json']) assert.equal((await fetch(server.playerUrl + path)).status, 404);
  assert.equal((await fetch(server.playerUrl + '/api/host/state')).status, 403);
  assert.equal((await fetch(server.playerUrl)).status, 200);
  const host = new URL(server.hostUrl).origin;
  assert.equal((await fetch(host + '/api/host/state')).status, 403);
  const login = await fetch(server.hostUrl, { redirect: 'manual' }); assert.equal(login.status, 303);
  const cookie = login.headers.get('set-cookie')!.split(';')[0];
  const response = await fetch(host + '/api/host/state', { headers: { Cookie: cookie } }); assert.equal(response.status, 200); assert.equal((await response.json()).lobby.capacity, 30);
  const post = (origin: string) => fetch(host + '/api/host/action', { method: 'POST', headers: { Cookie: cookie, Origin: origin, 'Content-Type': 'application/json' }, body: JSON.stringify({ kind: 'duration', value: 90 }) });
  assert.equal((await post('https://evil.example')).status, 403); assert.equal((await post(host)).status, 200); assert.equal(server.engine.defaultDuration, 90);
  const forgedHostStatus = await new Promise<number | undefined>((resolve, reject) => { const req = get(host, { headers: { Host: 'evil.example', Cookie: cookie } }, res => { res.resume(); resolve(res.statusCode); }); req.on('error', reject); });
  assert.equal(forgedHostStatus, 403);
});
test('real WebSocket sessions create isolated rooms, reject full joins, and resume with same token', async t => {
  const server = await startServers(); t.after(() => server.stop()); const clients: Socket[] = []; t.after(() => clients.forEach(s => s.close()));
  const a = await connect(server.playerUrl), d = await connect(server.playerUrl), c = await connect(server.playerUrl); clients.push(a.socket, d.socket, c.socket);
  assert.ok((await send(a.socket, { kind: 'name', name: '<script>alert(1)</script>' })).ok === false);
  assert.ok((await send(a.socket, { kind: 'create', mode: 'duo', role: 'attack', duration: 30 })).ok);
  const room = server.engine.playerView(a.session.id)!;
  assert.ok((await send(d.socket, { kind: 'join', code: room.code })).ok);
  assert.equal((await send(c.socket, { kind: 'join', code: room.code })).code, 'FULL');
  assert.ok((await send(c.socket, { kind: 'create', mode: 'solo', role: 'defense', duration: 60 })).ok);
  assert.notEqual(server.engine.playerView(c.session.id)!.id, room.id);
  const observed: RoomView[] = []; c.socket.on('room', r => { if (r) observed.push(r); });
  await new Promise(r => setTimeout(r, 250)); assert.ok(observed.length > 0); assert.ok(observed.every(r => r.id !== room.id));
  assert.ok(!JSON.stringify(room).includes(a.session.token));
  d.socket.disconnect(); await new Promise(r => setTimeout(r, 30)); const resumed = await connect(server.playerUrl, d.session.token); clients.push(resumed.socket); assert.equal(resumed.session.id, d.session.id); assert.equal(resumed.session.roomId, room.id);
  const replacement = await connect(server.playerUrl, a.session.token); clients.push(replacement.socket); await new Promise(r => setTimeout(r, 30)); assert.equal(a.socket.connected, false); assert.equal(server.engine.players.get(a.session.id)!.connected, true);
});
test('cross-origin WebSocket handshakes and unknown reconnection credentials are rejected', async t => {
  const server = await startServers(); t.after(() => server.stop());
  await assert.rejects(() => connect(server.playerUrl, 'wrong'));
  await new Promise<void>((resolve, reject) => { const s = io(server.playerUrl, { transports: ['websocket'], extraHeaders: { Origin: 'https://evil.example' }, reconnection: false }); s.once('connect', () => { s.close(); reject(new Error('Unexpected connection')); }); s.once('connect_error', () => { s.close(); resolve(); }); });
  assert.equal(server.engine.players.size, 0);
});
test('only the authenticated host can enable surrender, broadcasts it and receives the resulting win', async t => {
  const server = await startServers(); t.after(() => server.stop());
  const client = await connect(server.playerUrl); t.after(() => client.socket.close());
  const host = new URL(server.hostUrl).origin;
  const login = await fetch(server.hostUrl, { redirect: 'manual' }), cookie = login.headers.get('set-cookie')!.split(';')[0];
  const post = (value: unknown, authenticated = true, origin = host) => fetch(host + '/api/host/action', { method: 'POST', headers: { ...(authenticated ? { Cookie: cookie } : {}), Origin: origin, 'Content-Type': 'application/json' }, body: JSON.stringify({ kind: 'allow-surrender', value }) });
  assert.equal((await fetch(server.playerUrl + '/api/health').then(r => r.json())).version, GAME_VERSION);
  assert.equal((await post(true, false)).status, 403); assert.equal((await post(true, true, 'https://elsewhere.example')).status, 403);
  assert.equal((await post('true')).status, 400); assert.equal(server.engine.allowSurrender, false);
  const updated = new Promise<LobbyView>(resolve => { const watch = (lobby: LobbyView) => { if (lobby.allowSurrender) { client.socket.off('lobby', watch); resolve(lobby); } }; client.socket.on('lobby', watch); });
  assert.equal((await post(true)).status, 200);
  assert.equal((await updated).allowSurrender, true);
  assert.ok((await send(client.socket, { kind: 'create', mode: 'solo', role: 'defense', duration: 30 })).ok);
  assert.ok((await send(client.socket, { kind: 'ready', ready: true })).ok);
  // Move this test room across countdown without waiting three real seconds.
  const room = server.engine.rooms.get(server.engine.playerView(client.session.id)!.id)!;
  room.deadline = performance.now(); server.engine.advance();
  assert.ok((await send(client.socket, { kind: 'surrender', roundId: room.roundId, seq: 1 })).ok);
  const state = await fetch(host + '/api/host/state', { headers: { Cookie: cookie } }).then(r => r.json());
  assert.equal(state.lobby.version, GAME_VERSION); assert.equal(state.rooms[0].winner, 'attack'); assert.match(state.rooms[0].reason, /投降/);
  assert.equal((await post(false)).status, 200); assert.equal(server.engine.allowSurrender, false);
});

test('ultimate mode requires authenticated host access and fourth-move requests remain scoped to their own round', async t => {
  const server = await startServers(); t.after(() => server.stop());
  const client = await connect(server.playerUrl); t.after(() => client.socket.close());
  const host = new URL(server.hostUrl).origin, login = await fetch(server.hostUrl, { redirect: 'manual' });
  const cookie = login.headers.get('set-cookie')!.split(';')[0];
  const post = (value: unknown, authenticated = true, origin = host) => fetch(host + '/api/host/action', { method: 'POST', headers: { ...(authenticated ? { Cookie: cookie } : {}), Origin: origin, 'Content-Type': 'application/json' }, body: JSON.stringify({ kind: 'ultimate-mode', value }) });
  assert.equal((await post(true, false)).status, 403); assert.equal((await post(true, true, 'https://elsewhere.example')).status, 403);
  assert.equal((await post('true')).status, 400); assert.equal(server.engine.lobby().ultimateMode, true);
  assert.equal((await post(false)).status, 200); assert.equal(server.engine.lobby().ultimateMode, false);
  const updated = new Promise<LobbyView>(resolve => { const watch = (l: LobbyView) => { if (l.ultimateMode) { client.socket.off('lobby', watch); resolve(l); } }; client.socket.on('lobby', watch); });
  assert.equal((await post(true)).status, 200); assert.equal((await updated).ultimateMode, true);
  await send(client.socket, { kind: 'create', mode: 'solo', role: 'attack', duration: 30 });
  await send(client.socket, { kind: 'ready', ready: true });
  const room = server.engine.rooms.get(server.engine.playerView(client.session.id)!.id)!;
  room.deadline = performance.now(); server.engine.advance();
  assert.equal((await send(client.socket, { kind: 'ultimate', roundId: room.roundId, seq: 1 })).code, 'ULTIMATE_CHARGING');
  server.engine.players.get(client.session.id)!.charge = 100;
  assert.equal((await send(client.socket, { kind: 'ultimate', roundId: 'another-round', seq: 2 })).code, 'STALE_ROUND');
  assert.ok((await send(client.socket, { kind: 'ultimate', roundId: room.roundId, seq: 2 })).ok);
  assert.equal((await send(client.socket, { kind: 'ultimate', roundId: room.roundId, seq: 2 })).code, 'STALE_INPUT');
  assert.equal((await post(false)).status, 200);
  const state = await fetch(host + '/api/host/state', { headers: { Cookie: cookie } }).then(r => r.json());
  assert.equal(state.lobby.ultimateMode, false); assert.equal(state.rooms[0].ultimateMode, true);
  assert.equal(state.rooms[0].members[0].ultimate.uses, 1); assert.ok(state.rooms[0].members[0].ultimate.remainingMs > 0);
});
